
version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api_server:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  ws_server:
    build:
      context: ./ws
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
